-- Expand keyword database with comprehensive categories and keywords
-- Current database has 71 keywords, expanding to 300+ keywords

-- Insurance Companies and Terms
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('ALLSTATE', 'builtin', 'insurance'),
('GEICO', 'builtin', 'insurance'),
('STATE FARM', 'builtin', 'insurance'),
('PROGRESSIVE', 'builtin', 'insurance'),
('FARMERS', 'builtin', 'insurance'),
('USAA', 'builtin', 'insurance'),
('LIBERTY MUTUAL', 'builtin', 'insurance'),
('NATIONWIDE', 'builtin', 'insurance'),
('AMERICAN FAMILY', 'builtin', 'insurance'),
('TRAVELERS', 'builtin', 'insurance'),
('METLIFE', 'builtin', 'insurance'),
('PRUDENTIAL', 'builtin', 'insurance'),
('NEW YORK LIFE', 'builtin', 'insurance'),
('MUTUAL OF OMAHA', 'builtin', 'insurance'),
('INSURANCE', 'builtin', 'insurance'),
('POLICY', 'builtin', 'insurance'),
('PREMIUM', 'builtin', 'insurance'),
('CLAIM', 'builtin', 'insurance'),
('COVERAGE', 'builtin', 'insurance'),
('DEDUCTIBLE', 'builtin', 'insurance'),

-- Educational Institutions
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('UNIVERSITY', 'builtin', 'education'),
('COLLEGE', 'builtin', 'education'),
('SCHOOL', 'builtin', 'education'),
('ACADEMY', 'builtin', 'education'),
('INSTITUTE', 'builtin', 'education'),
('HARVARD', 'builtin', 'education'),
('STANFORD', 'builtin', 'education'),
('MIT', 'builtin', 'education'),
('UCLA', 'builtin', 'education'),
('USC', 'builtin', 'education'),
('BERKELEY', 'builtin', 'education'),
('YALE', 'builtin', 'education'),
('PRINCETON', 'builtin', 'education'),
('COLUMBIA', 'builtin', 'education'),
('NYU', 'builtin', 'education'),
('COMMUNITY COLLEGE', 'builtin', 'education'),
('STATE UNIVERSITY', 'builtin', 'education'),
('TECHNICAL COLLEGE', 'builtin', 'education'),
('TRAINING CENTER', 'builtin', 'education'),
('LEARNING CENTER', 'builtin', 'education'),

-- Real Estate and Property Management
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('REAL ESTATE', 'builtin', 'real_estate'),
('PROPERTY MANAGEMENT', 'builtin', 'real_estate'),
('REALTY', 'builtin', 'real_estate'),
('REALTOR', 'builtin', 'real_estate'),
('APARTMENTS', 'builtin', 'real_estate'),
('CONDOS', 'builtin', 'real_estate'),
('HOUSING', 'builtin', 'real_estate'),
('RENTAL', 'builtin', 'real_estate'),
('LEASE', 'builtin', 'real_estate'),
('MORTGAGE', 'builtin', 'real_estate'),
('ESCROW', 'builtin', 'real_estate'),
('TITLE COMPANY', 'builtin', 'real_estate'),
('BROKER', 'builtin', 'real_estate'),
('AGENT', 'builtin', 'real_estate'),
('COLDWELL BANKER', 'builtin', 'real_estate'),
('CENTURY 21', 'builtin', 'real_estate'),
('RE/MAX', 'builtin', 'real_estate'),
('KELLER WILLIAMS', 'builtin', 'real_estate'),
('ZILLOW', 'builtin', 'real_estate'),
('TRULIA', 'builtin', 'real_estate'),

-- Transportation and Logistics
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('FEDEX', 'builtin', 'transportation'),
('UPS', 'builtin', 'transportation'),
('DHL', 'builtin', 'transportation'),
('USPS', 'builtin', 'transportation'),
('SHIPPING', 'builtin', 'transportation'),
('FREIGHT', 'builtin', 'transportation'),
('LOGISTICS', 'builtin', 'transportation'),
('DELIVERY', 'builtin', 'transportation'),
('TRANSPORT', 'builtin', 'transportation'),
('TRUCKING', 'builtin', 'transportation'),
('AIRLINE', 'builtin', 'transportation'),
('AIRPORT', 'builtin', 'transportation'),
('BUS', 'builtin', 'transportation'),
('METRO', 'builtin', 'transportation'),
('SUBWAY', 'builtin', 'transportation'),
('TAXI', 'builtin', 'transportation'),
('UBER', 'builtin', 'transportation'),
('LYFT', 'builtin', 'transportation'),
('RENTAL CAR', 'builtin', 'transportation'),
('MOVING COMPANY', 'builtin', 'transportation'),

-- Food and Restaurant Chains
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('MCDONALDS', 'builtin', 'food_restaurant'),
('BURGER KING', 'builtin', 'food_restaurant'),
('SUBWAY', 'builtin', 'food_restaurant'),
('STARBUCKS', 'builtin', 'food_restaurant'),
('KFC', 'builtin', 'food_restaurant'),
('PIZZA HUT', 'builtin', 'food_restaurant'),
('DOMINOS', 'builtin', 'food_restaurant'),
('TACO BELL', 'builtin', 'food_restaurant'),
('WENDYS', 'builtin', 'food_restaurant'),
('CHIPOTLE', 'builtin', 'food_restaurant'),
('PANERA', 'builtin', 'food_restaurant'),
('DUNKIN', 'builtin', 'food_restaurant'),
('RESTAURANT', 'builtin', 'food_restaurant'),
('CAFE', 'builtin', 'food_restaurant'),
('DINER', 'builtin', 'food_restaurant'),
('BISTRO', 'builtin', 'food_restaurant'),
('GRILL', 'builtin', 'food_restaurant'),
('BAKERY', 'builtin', 'food_restaurant'),
('CATERING', 'builtin', 'food_restaurant'),
('FOOD SERVICE', 'builtin', 'food_restaurant'),

-- Retail and Shopping
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('WALMART', 'builtin', 'retail'),
('TARGET', 'builtin', 'retail'),
('AMAZON', 'builtin', 'retail'),
('COSTCO', 'builtin', 'retail'),
('SAMS CLUB', 'builtin', 'retail'),
('BJS', 'builtin', 'retail'),
('HOME DEPOT', 'builtin', 'retail'),
('LOWES', 'builtin', 'retail'),
('BEST BUY', 'builtin', 'retail'),
('MACYS', 'builtin', 'retail'),
('NORDSTROM', 'builtin', 'retail'),
('KOHLS', 'builtin', 'retail'),
('JC PENNEY', 'builtin', 'retail'),
('SEARS', 'builtin', 'retail'),
('CVS', 'builtin', 'retail'),
('WALGREENS', 'builtin', 'retail'),
('RITE AID', 'builtin', 'retail'),
('GROCERY', 'builtin', 'retail'),
('SUPERMARKET', 'builtin', 'retail'),
('DEPARTMENT STORE', 'builtin', 'retail'),

-- Entertainment and Media
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('NETFLIX', 'builtin', 'entertainment'),
('DISNEY', 'builtin', 'entertainment'),
('HULU', 'builtin', 'entertainment'),
('HBO', 'builtin', 'entertainment'),
('SPOTIFY', 'builtin', 'entertainment'),
('APPLE MUSIC', 'builtin', 'entertainment'),
('YOUTUBE', 'builtin', 'entertainment'),
('STREAMING', 'builtin', 'entertainment'),
('CABLE', 'builtin', 'entertainment'),
('SATELLITE', 'builtin', 'entertainment'),
('THEATER', 'builtin', 'entertainment'),
('CINEMA', 'builtin', 'entertainment'),
('MOVIE', 'builtin', 'entertainment'),
('CONCERT', 'builtin', 'entertainment'),
('STADIUM', 'builtin', 'entertainment'),
('ARENA', 'builtin', 'entertainment'),
('CASINO', 'builtin', 'entertainment'),
('GAMING', 'builtin', 'entertainment'),
('ENTERTAINMENT', 'builtin', 'entertainment'),
('MEDIA', 'builtin', 'entertainment'),

-- Non-Profit Organizations
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('RED CROSS', 'builtin', 'nonprofit'),
('SALVATION ARMY', 'builtin', 'nonprofit'),
('GOODWILL', 'builtin', 'nonprofit'),
('UNITED WAY', 'builtin', 'nonprofit'),
('YMCA', 'builtin', 'nonprofit'),
('YWCA', 'builtin', 'nonprofit'),
('BOYS AND GIRLS CLUB', 'builtin', 'nonprofit'),
('HABITAT FOR HUMANITY', 'builtin', 'nonprofit'),
('AMERICAN CANCER SOCIETY', 'builtin', 'nonprofit'),
('AMERICAN HEART ASSOCIATION', 'builtin', 'nonprofit'),
('UNICEF', 'builtin', 'nonprofit'),
('OXFAM', 'builtin', 'nonprofit'),
('NONPROFIT', 'builtin', 'nonprofit'),
('FOUNDATION', 'builtin', 'nonprofit'),
('CHARITY', 'builtin', 'nonprofit'),
('DONATION', 'builtin', 'nonprofit'),
('VOLUNTEER', 'builtin', 'nonprofit'),
('RELIEF', 'builtin', 'nonprofit'),
('HUMANITARIAN', 'builtin', 'nonprofit'),
('COMMUNITY CENTER', 'builtin', 'nonprofit'),

-- Expanded Automotive
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('TOYOTA', 'builtin', 'automotive'),
('HONDA', 'builtin', 'automotive'),
('NISSAN', 'builtin', 'automotive'),
('HYUNDAI', 'builtin', 'automotive'),
('KIA', 'builtin', 'automotive'),
('SUBARU', 'builtin', 'automotive'),
('MAZDA', 'builtin', 'automotive'),
('MITSUBISHI', 'builtin', 'automotive'),
('VOLKSWAGEN', 'builtin', 'automotive'),
('BMW', 'builtin', 'automotive'),
('MERCEDES', 'builtin', 'automotive'),
('AUDI', 'builtin', 'automotive'),
('LEXUS', 'builtin', 'automotive'),
('INFINITI', 'builtin', 'automotive'),
('ACURA', 'builtin', 'automotive'),
('CADILLAC', 'builtin', 'automotive'),
('LINCOLN', 'builtin', 'automotive'),
('BUICK', 'builtin', 'automotive'),
('PONTIAC', 'builtin', 'automotive'),
('OLDSMOBILE', 'builtin', 'automotive'),
('SATURN', 'builtin', 'automotive'),
('HUMMER', 'builtin', 'automotive'),
('JEEP', 'builtin', 'automotive'),
('DODGE', 'builtin', 'automotive'),
('CHRYSLER', 'builtin', 'automotive'),
('PLYMOUTH', 'builtin', 'automotive'),
('TESLA', 'builtin', 'automotive'),
('RIVIAN', 'builtin', 'automotive'),
('LUCID', 'builtin', 'automotive'),
('AUTO REPAIR', 'builtin', 'automotive'),
('MECHANIC', 'builtin', 'automotive'),
('SERVICE CENTER', 'builtin', 'automotive'),
('PARTS', 'builtin', 'automotive'),
('MAINTENANCE', 'builtin', 'automotive'),

-- Expanded Business Entity Types
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('CORPORATION', 'builtin', 'business'),
('INCORPORATED', 'builtin', 'business'),
('LIMITED LIABILITY', 'builtin', 'business'),
('PARTNERSHIP', 'builtin', 'business'),
('PROPRIETORSHIP', 'builtin', 'business'),
('ENTERPRISE', 'builtin', 'business'),
('VENTURES', 'builtin', 'business'),
('HOLDINGS', 'builtin', 'business'),
('MANAGEMENT', 'builtin', 'business'),
('CONSULTING', 'builtin', 'business'),
('ADVISORY', 'builtin', 'business'),
('SOLUTIONS', 'builtin', 'business'),
('SERVICES', 'builtin', 'business'),
('SYSTEMS', 'builtin', 'business'),
('TECHNOLOGIES', 'builtin', 'business'),
('INNOVATIONS', 'builtin', 'business'),
('DEVELOPMENT', 'builtin', 'business'),
('OPERATIONS', 'builtin', 'business'),
('LOGISTICS', 'builtin', 'business'),
('DISTRIBUTION', 'builtin', 'business'),

-- Expanded Financial Institutions
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('JPMORGAN', 'builtin', 'financial'),
('MORGAN STANLEY', 'builtin', 'financial'),
('GOLDMAN SACHS', 'builtin', 'financial'),
('MERRILL LYNCH', 'builtin', 'financial'),
('EDWARD JONES', 'builtin', 'financial'),
('CHARLES SCHWAB', 'builtin', 'financial'),
('FIDELITY', 'builtin', 'financial'),
('VANGUARD', 'builtin', 'financial'),
('TD AMERITRADE', 'builtin', 'financial'),
('E-TRADE', 'builtin', 'financial'),
('ROBINHOOD', 'builtin', 'financial'),
('COINBASE', 'builtin', 'financial'),
('PAYPAL', 'builtin', 'financial'),
('VENMO', 'builtin', 'financial'),
('ZELLE', 'builtin', 'financial'),
('CASHAPP', 'builtin', 'financial'),
('WESTERN UNION', 'builtin', 'financial'),
('MONEYGRAM', 'builtin', 'financial'),
('INVESTMENT', 'builtin', 'financial'),
('BROKERAGE', 'builtin', 'financial'),

-- Common Business Suffixes and Terms
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('LLC', 'builtin', 'business'),
('LTD', 'builtin', 'business'),
('CORP', 'builtin', 'business'),
('INC', 'builtin', 'business'),
('LP', 'builtin', 'business'),
('LLP', 'builtin', 'business'),
('PLLC', 'builtin', 'business'),
('CO', 'builtin', 'business'),
('COMPANY', 'builtin', 'business'),
('ASSOCIATES', 'builtin', 'business'),
('PARTNERS', 'builtin', 'business'),
('GROUP', 'builtin', 'business'),
('FIRM', 'builtin', 'business'),
('AGENCY', 'builtin', 'business'),
('BUREAU', 'builtin', 'business'),
('OFFICE', 'builtin', 'business'),
('CENTER', 'builtin', 'business'),
('INSTITUTE', 'builtin', 'business'),
('ASSOCIATION', 'builtin', 'business'),
('ORGANIZATION', 'builtin', 'business');

-- Update any existing keyword counts/stats
UPDATE exclusion_keywords SET updated_at = now() WHERE keyword_type = 'builtin';
