-- Comprehensive keyword restoration - Adding all missing keywords to reach 500+
-- Using ON CONFLICT DO NOTHING to prevent duplicate key violations

-- Core Business Keywords
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('ACCOUNTING OFFICE', 'builtin', 'business'),
('ACCOUNTS PAYABLE', 'builtin', 'business'),
('ADJUDICATION', 'builtin', 'business'),
('ADMINISTRATION', 'builtin', 'business'),
('ADP', 'builtin', 'business'),
('ADVANTA', 'builtin', 'business'),
('AEP', 'builtin', 'business'),
('AETNA', 'builtin', 'business'),
('aflac', 'builtin', 'business'),
('AGENCY', 'builtin', 'business'),
('AGRICULTURAL', 'builtin', 'business'),
('AIG', 'builtin', 'business'),
('alabama power', 'builtin', 'business'),
('alagasco', 'builtin', 'business'),
('ALLY', 'builtin', 'business'),
('ALPHERA FINANCIAL', 'builtin', 'business'),
('ALTRIA', 'builtin', 'business'),
('AMERICAN ELECTRIC', 'builtin', 'business'),
('AMERICAN EXPRESS', 'builtin', 'business'),
('AMERICAN FAMILY', 'builtin', 'business'),
('AMERIPRISE', 'builtin', 'business'),
('ameris bank', 'builtin', 'business'),
('AMERISURE', 'builtin', 'business'),
('AMEX', 'builtin', 'business'),
('AMICA', 'builtin', 'business'),
('ANNUITY', 'builtin', 'business'),
('ANTHEM', 'builtin', 'business'),
('ARBITRATION', 'builtin', 'business'),
('archer energy', 'builtin', 'business'),
('ARCHIVES', 'builtin', 'business'),
('ARIZONA PUBLIC SERVICE', 'builtin', 'business'),
('ARMY', 'builtin', 'business'),
('ARVEST BANK', 'builtin', 'business'),
('ASSET MANAGEMENT', 'builtin', 'business'),
('ASSURANCE', 'builtin', 'business'),
('ASYLUM', 'builtin', 'business'),
('AT & T', 'builtin', 'business'),
('AT&T', 'builtin', 'business'),
('ATT', 'builtin', 'business'),
('AUDIT', 'builtin', 'business'),
('AURORA ENERGY', 'builtin', 'business'),
('AUSTIN ENERGY', 'builtin', 'business'),
('AUTHORITY', 'builtin', 'business'),
('AVISTA', 'builtin', 'business'),
('AXA', 'builtin', 'business')
ON CONFLICT DO NOTHING;

-- Financial Keywords
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('BANC', 'builtin', 'financial'),
('BANC CORP', 'builtin', 'financial'),
('BANCORP', 'builtin', 'financial'),
('BANK', 'builtin', 'financial'),
('Bank of', 'builtin', 'financial'),
('BANK OF AMERICA', 'builtin', 'financial'),
('BANKCORP', 'builtin', 'financial'),
('BARCLAYS', 'builtin', 'financial'),
('BROKER', 'builtin', 'financial'),
('BROKERAGE', 'builtin', 'financial'),
('CAPITAL', 'builtin', 'financial'),
('CAPITAL GROUP', 'builtin', 'financial'),
('CAPITAL ONE', 'builtin', 'financial'),
('CAPITOL', 'builtin', 'financial'),
('CAPTIVE FINANCE', 'builtin', 'financial'),
('CARMAX AUTO FINANCE', 'builtin', 'financial'),
('CATERPILLAR FINANCIAL', 'builtin', 'financial'),
('CELTIC BANK', 'builtin', 'financial'),
('CENTRAL BANK', 'builtin', 'financial'),
('CHARLES SCHWAB', 'builtin', 'financial'),
('CHASE', 'builtin', 'financial'),
('CHEVRON CREDIT', 'builtin', 'financial'),
('CITI', 'builtin', 'financial'),
('citi bank', 'builtin', 'financial'),
('CITIBANK', 'builtin', 'financial'),
('COBANK', 'builtin', 'financial'),
('COCA‑COLA CREDIT UNION', 'builtin', 'financial'),
('commercial card', 'builtin', 'financial'),
('commerence bank', 'builtin', 'financial'),
('COMMUNITY BANK', 'builtin', 'financial'),
('CREDIT', 'builtin', 'financial'),
('CREDIT ACCEPTANCE', 'builtin', 'financial'),
('CREDIT CARD', 'builtin', 'financial'),
('CREDIT CORP', 'builtin', 'financial'),
('CREDIT ONE', 'builtin', 'financial'),
('CREDIT UNION', 'builtin', 'financial'),
('CREDITORS', 'builtin', 'financial'),
('CUSTODIAN', 'builtin', 'financial'),
('DEBT', 'builtin', 'financial'),
('DEBT COLLECTION', 'builtin', 'financial'),
('DEPOSITORY', 'builtin', 'financial'),
('EASTERN BANK', 'builtin', 'financial'),
('EATON VANCE', 'builtin', 'financial'),
('ELEMENT FLEET', 'builtin', 'financial'),
('EQUITY TRUST', 'builtin', 'financial'),
('ERICSSON CREDIT', 'builtin', 'financial'),
('ESCROW', 'builtin', 'financial'),
('EXPRESS SCRIPTS', 'builtin', 'financial'),
('F&B', 'builtin', 'financial'),
('family trust', 'builtin', 'financial'),
('FANNIE MAE', 'builtin', 'financial'),
('FARM BUREAU', 'builtin', 'financial'),
('FARM CREDIT', 'builtin', 'financial'),
('farmers and merchants bank', 'builtin', 'financial'),
('FARMERS INSURANCE', 'builtin', 'financial'),
('FDIC', 'builtin', 'financial'),
('FEDERAL RESERVE', 'builtin', 'financial'),
('FIDELITY', 'builtin', 'financial'),
('FIDUCIARY', 'builtin', 'financial'),
('FIFTH THIRD', 'builtin', 'financial'),
('FINANCE', 'builtin', 'financial'),
('FINANCE AND INSURANCE', 'builtin', 'financial'),
('FINANCIAL', 'builtin', 'financial'),
('FINANCIAL ENFORCEMENT', 'builtin', 'financial'),
('FIRM', 'builtin', 'financial'),
('first american title', 'builtin', 'financial'),
('FISCAL SERVICE', 'builtin', 'financial'),
('FISCAL SERVICES', 'builtin', 'financial'),
('FLEET', 'builtin', 'financial'),
('foundation', 'builtin', 'financial'),
('FUND', 'builtin', 'financial'),
('FUNDING', 'builtin', 'financial'),
('FUNDS', 'builtin', 'financial'),
('FUTURES', 'builtin', 'financial'),
('GE CAPITAL', 'builtin', 'financial'),
('GE HEALTHCARE FINANCE', 'builtin', 'financial'),
('GEICO', 'builtin', 'financial'),
('GM FINANCIAL', 'builtin', 'financial'),
('GRACE PERIOD TRUST', 'builtin', 'financial'),
('GREEN DOT BANK', 'builtin', 'financial'),
('GUARDIAN LIFE', 'builtin', 'financial'),
('HARTFORD', 'builtin', 'financial'),
('HEALTH INSURANCE', 'builtin', 'financial'),
('HIGHMARK', 'builtin', 'financial'),
('HOLDINGS', 'builtin', 'financial'),
('HOME EQUITY', 'builtin', 'financial'),
('HOUSING FINANCE', 'builtin', 'financial'),
('HONDA FINANCE', 'builtin', 'financial'),
('HUNTINGTON BANCSHARES', 'builtin', 'financial'),
('HYUNDAI', 'builtin', 'financial'),
('INDIVIDUAL ACH PAYMENT', 'builtin', 'financial'),
('INSURANCE', 'builtin', 'financial'),
('INSURANCE COMMISSION', 'builtin', 'financial'),
('INSURER', 'builtin', 'financial'),
('INTERNAL TRANSFER', 'builtin', 'financial'),
('INTERNATIONAL MONETARY', 'builtin', 'financial'),
('INVESTMENT', 'builtin', 'financial'),
('INVESTMENT BOARD', 'builtin', 'financial'),
('INVESTORS', 'builtin', 'financial'),
('JP', 'builtin', 'financial'),
('JP MORGAN', 'builtin', 'financial'),
('JPMORGAN', 'builtin', 'financial'),
('KAISER', 'builtin', 'financial'),
('LASALLE BANK', 'builtin', 'financial'),
('LEASE', 'builtin', 'financial'),
('LEASE FINANCING', 'builtin', 'financial'),
('LENDING', 'builtin', 'financial'),
('LENDING CLUB', 'builtin', 'financial'),
('LIBERTY MUTUAL', 'builtin', 'financial'),
('LINE OF CREDIT', 'builtin', 'financial'),
('LOAN', 'builtin', 'financial'),
('LOAN PAYMENT', 'builtin', 'financial'),
('LOAN SERVICING', 'builtin', 'financial'),
('LOCKHEED MARTIN FCU', 'builtin', 'financial'),
('LPL FINANCIAL', 'builtin', 'financial'),
('M&T', 'builtin', 'financial'),
('MANUFACTURERS AND TRADERS', 'builtin', 'financial'),
('MAPFRE', 'builtin', 'financial'),
('MARGIN', 'builtin', 'financial'),
('MARSH', 'builtin', 'financial'),
('MARSH & MCLENNAN', 'builtin', 'financial'),
('MAZDA', 'builtin', 'financial'),
('MB FINANCIAL', 'builtin', 'financial'),
('MEDICARE REIMBURSEMENT', 'builtin', 'financial'),
('MEDTRONIC FINANCE', 'builtin', 'financial'),
('MELLON', 'builtin', 'financial'),
('MERCEDES BENZ FINANCIAL', 'builtin', 'financial'),
('merrill lynch', 'builtin', 'financial'),
('MERS', 'builtin', 'financial'),
('METLIFE', 'builtin', 'financial'),
('MILLIMAN BENEFITS', 'builtin', 'financial'),
('MIZUHO', 'builtin', 'financial'),
('MORGAN', 'builtin', 'financial'),
('MORGAN STANLEY', 'builtin', 'financial'),
('MORTGAGE', 'builtin', 'financial'),
('MORTGAGE COMPANY', 'builtin', 'financial'),
('MORTGAGE SERVICING', 'builtin', 'financial'),
('NATIONAL BANK', 'builtin', 'financial'),
('NATIONAL FINANCE', 'builtin', 'financial'),
('NATIONAL TREASURY', 'builtin', 'financial'),
('NISSAN MOTOR ACCEPTANCE', 'builtin', 'financial'),
('NORTHWESTERN MUTUAL', 'builtin', 'financial'),
('OCEAN VIEW INSURANCE', 'builtin', 'financial'),
('OLD MUTUAL', 'builtin', 'financial'),
('PARKER HANNIFIN CREDIT', 'builtin', 'financial'),
('PENN Y M N C', 'builtin', 'financial'),
('PENNYMAC', 'builtin', 'financial'),
('PENSION', 'builtin', 'financial'),
('PENSION FUND', 'builtin', 'financial'),
('PERSHING', 'builtin', 'financial'),
('PHYSICIANS MUTUAL', 'builtin', 'financial'),
('PILGRIM', 'builtin', 'financial'),
('PIMCO', 'builtin', 'financial'),
('PNC', 'builtin', 'financial'),
('PRA GROUP', 'builtin', 'financial'),
('PRINCIPAL', 'builtin', 'financial'),
('PROGRESSIVE', 'builtin', 'financial'),
('PRUDENTIAL', 'builtin', 'financial'),
('REAL ESTATE', 'builtin', 'financial'),
('REAL ESTATE AND RENTAL AND LEASING', 'builtin', 'financial'),
('REGIONAL BANK', 'builtin', 'financial'),
('retirement', 'builtin', 'financial'),
('REVOLVING FUND', 'builtin', 'financial'),
('ROYAL BANK', 'builtin', 'financial'),
('RSA', 'builtin', 'financial'),
('SAVINGS', 'builtin', 'financial'),
('SAVINGS & LOAN', 'builtin', 'financial'),
('SCHWAB', 'builtin', 'financial'),
('SEC', 'builtin', 'financial'),
('SECURITIES', 'builtin', 'financial'),
('SECURITIES COMMISSION', 'builtin', 'financial'),
('SECURITY LIFE', 'builtin', 'financial'),
('SETTLEMENT', 'builtin', 'financial'),
('SIGNAL MUTUAL', 'builtin', 'financial'),
('STELLANTIS', 'builtin', 'financial'),
('SUPPLEMENTAL INSURANCE', 'builtin', 'financial'),
('SYNNOVUS', 'builtin', 'financial'),
('TD', 'builtin', 'financial'),
('THE CAPITAL GROUP', 'builtin', 'financial'),
('TIAA', 'builtin', 'financial'),
('TOYOTA FINANCIAL', 'builtin', 'financial'),
('travelers', 'builtin', 'financial'),
('TRUST', 'builtin', 'financial'),
('TRUST COMPANY', 'builtin', 'financial'),
('TRUSTEE', 'builtin', 'financial'),
('TRUSTEES', 'builtin', 'financial'),
('UAW TRUST', 'builtin', 'financial'),
('UHC', 'builtin', 'financial'),
('UNEMPLOYMENT', 'builtin', 'financial'),
('UNION', 'builtin', 'financial'),
('UNITED HEALTH', 'builtin', 'financial'),
('united healthcare', 'builtin', 'financial'),
('UNIVERSITY', 'builtin', 'financial'),
('US BANK', 'builtin', 'financial'),
('USAA', 'builtin', 'financial'),
('USAA FEDERAL SAVINGS', 'builtin', 'financial'),
('usi insurance', 'builtin', 'financial'),
('VANGUARD', 'builtin', 'financial'),
('VISA', 'builtin', 'financial'),
('WAGE', 'builtin', 'financial'),
('WAGES', 'builtin', 'financial'),
('WELLS FARGO', 'builtin', 'financial'),
('WESTERN ALLIANCE BANK', 'builtin', 'financial'),
('WEX', 'builtin', 'financial'),
('WIRE', 'builtin', 'financial'),
('WIRE TRANSFER', 'builtin', 'financial'),
('WORKERS COMPENSATION', 'builtin', 'financial'),
('ZIONS', 'builtin', 'financial'),
('ZIONS BANK', 'builtin', 'financial'),
('ZURICH', 'builtin', 'financial')
ON CONFLICT DO NOTHING;

-- Government Keywords
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('ARMY', 'builtin', 'government'),
('BOARD', 'builtin', 'government'),
('BOARD OF EDUCATION', 'builtin', 'government'),
('board of trustees', 'builtin', 'government'),
('BOND', 'builtin', 'government'),
('BORDER', 'builtin', 'government'),
('BOROUGH', 'builtin', 'government'),
('BUREAU', 'builtin', 'government'),
('CALIFORNIA DEPARTMENT', 'builtin', 'government'),
('CALPERS', 'builtin', 'government'),
('census bureau', 'builtin', 'government'),
('CERRO GORDO COUNTY', 'builtin', 'government'),
('chamber of commerce', 'builtin', 'government'),
('child support', 'builtin', 'government'),
('CIRCUIT COURT', 'builtin', 'government'),
('CITY', 'builtin', 'government'),
('CITY LIGHT', 'builtin', 'government'),
('CITY OF', 'builtin', 'government'),
('city treasurer', 'builtin', 'government'),
('CITY UTILITIES', 'builtin', 'government'),
('CIVIC CENTER', 'builtin', 'government'),
('COLLEGE', 'builtin', 'government'),
('COMMISSION', 'builtin', 'government'),
('COMMITTEE', 'builtin', 'government'),
('COMMONWEALTH', 'builtin', 'government'),
('commonwealth of', 'builtin', 'government'),
('COMMUNITY COLLEGE', 'builtin', 'government'),
('COMPENSATION', 'builtin', 'government'),
('COMPTROLLER', 'builtin', 'government'),
('CONSERVANCY', 'builtin', 'government'),
('CONSORTIUM', 'builtin', 'government'),
('CONTROLLER', 'builtin', 'government'),
('COOPERATIVE', 'builtin', 'government'),
('CORPS OF ENGINEERS', 'builtin', 'government'),
('CORRECTIONAL', 'builtin', 'government'),
('CORRECTIONS', 'builtin', 'government'),
('COUNTY', 'builtin', 'government'),
('county assessor', 'builtin', 'government'),
('county of', 'builtin', 'government'),
('county tax collector', 'builtin', 'government'),
('county treasurer', 'builtin', 'government'),
('COURT', 'builtin', 'government'),
('CUSTOMS', 'builtin', 'government'),
('DEFENSE', 'builtin', 'government'),
('DEFERRED COMP', 'builtin', 'government'),
('DEPARTMENT', 'builtin', 'government'),
('department of labor', 'builtin', 'government'),
('department of revenue', 'builtin', 'government'),
('department of taxation', 'builtin', 'government'),
('dept of revenue', 'builtin', 'government'),
('dept of taxation', 'builtin', 'government'),
('disbursement', 'builtin', 'government'),
('DIVISION', 'builtin', 'government'),
('DOD', 'builtin', 'government'),
('DOT', 'builtin', 'government'),
('ELIGIBILITY OFFICE', 'builtin', 'government'),
('EMPLOYEE', 'builtin', 'government'),
('EMPLOYEE BENEFIT', 'builtin', 'government'),
('EMPLOYEE BENEFIT BOARD', 'builtin', 'government'),
('EMPLOYEE EXPENSE', 'builtin', 'government'),
('EMPLOYEES RETIREMENT', 'builtin', 'government'),
('ENFORCEMENT', 'builtin', 'government'),
('ENVIRONMENTAL', 'builtin', 'government'),
('EQUAL OPPORTUNITY', 'builtin', 'government'),
('EXCISE', 'builtin', 'government'),
('EXPENSE REIMBURSEMENT', 'builtin', 'government'),
('FBI', 'builtin', 'government'),
('FEDERAL', 'builtin', 'government'),
('FEDERAL EXPRESS FREIGHT', 'builtin', 'government'),
('FEDEX FREIGHT PAYMENT', 'builtin', 'government'),
('FEMA', 'builtin', 'government'),
('FORESTRY', 'builtin', 'government'),
('FRANCHISE TAX', 'builtin', 'government'),
('GAMING COMMISSION', 'builtin', 'government'),
('GENERAL SERVICES', 'builtin', 'government'),
('GOVERNING BOARD', 'builtin', 'government'),
('GOVERNMENT', 'builtin', 'government'),
('GOVERNOR', 'builtin', 'government'),
('GRANT', 'builtin', 'government'),
('HARBOR', 'builtin', 'government'),
('HEALTH AND HUMAN SERVICES', 'builtin', 'government'),
('HEALTH BENEFIT FUND', 'builtin', 'government'),
('HEALTH DEPARTMENT', 'builtin', 'government'),
('HOMELAND SECURITY', 'builtin', 'government'),
('HOUSING AUTHORITY', 'builtin', 'government'),
('HUD', 'builtin', 'government'),
('IMMIGRATION', 'builtin', 'government'),
('IMPORT EXPORT', 'builtin', 'government'),
('INDUSTRIAL DEVELOPMENT', 'builtin', 'government'),
('INDUSTRIAL RELATIONS', 'builtin', 'government'),
('INSPECTION', 'builtin', 'government'),
('INSPECTORATE', 'builtin', 'government'),
('INTELLECTUAL PROPERTY', 'builtin', 'government'),
('INTERCOMPANY', 'builtin', 'government'),
('INTERNAL REVENUE', 'builtin', 'government'),
('internal revenue service', 'builtin', 'government'),
('IRS', 'builtin', 'government'),
('ISO', 'builtin', 'government'),
('JUDICIARY', 'builtin', 'government'),
('LABOR DEPARTMENT', 'builtin', 'government'),
('LAND MANAGEMENT', 'builtin', 'government'),
('LEGISLATURE', 'builtin', 'government'),
('LOTTERY COMMISSION', 'builtin', 'government'),
('MARITIME', 'builtin', 'government'),
('MEDICAID', 'builtin', 'government'),
('MEDICARE', 'builtin', 'government'),
('MILITARY', 'builtin', 'government'),
('MINING', 'builtin', 'government'),
('MTA', 'builtin', 'government'),
('MUNICIPAL', 'builtin', 'government'),
('MUNICIPAL ELECTRIC', 'builtin', 'government'),
('MUNICIPAL POWER', 'builtin', 'government'),
('MUNICIPALITY', 'builtin', 'government'),
('mututal of omaha', 'builtin', 'government'),
('NAVY', 'builtin', 'government'),
('NUCLEAR', 'builtin', 'government'),
('OCCUPATIONAL SAFETY', 'builtin', 'government'),
('OFFICE OF', 'builtin', 'government'),
('OFFICE OF MANAGEMENT', 'builtin', 'government'),
('OFFICE SUPPLY REIMBURSEMENT', 'builtin', 'government'),
('OPERATIONS', 'builtin', 'government'),
('petty cash', 'builtin', 'government'),
('PHARMACY', 'builtin', 'government'),
('PORT AUTHORITY', 'builtin', 'government'),
('POSTAL', 'builtin', 'government'),
('POWER AUTHORITY', 'builtin', 'government'),
('PROBATION', 'builtin', 'government'),
('PROCURATOR', 'builtin', 'government'),
('PROCUREMENT', 'builtin', 'government'),
('PUBLIC BROADCASTING', 'builtin', 'government'),
('PUBLIC HEALTH', 'builtin', 'government'),
('PUBLIC SAFETY', 'builtin', 'government'),
('PUBLIC SERVICE COMMISSION', 'builtin', 'government'),
('PUBLIC UTILITIES', 'builtin', 'government'),
('PUBLIC UTILITIES COMMISSION', 'builtin', 'government'),
('PUBLIC UTILITY', 'builtin', 'government'),
('PUBLIC WORKS', 'builtin', 'government'),
('PURCHASE CARD PAYMENT', 'builtin', 'government'),
('RAILROAD', 'builtin', 'government'),
('RECLAMATION', 'builtin', 'government'),
('REDEVELOPMENT', 'builtin', 'government'),
('REGENTS', 'builtin', 'government'),
('REGULATORY', 'builtin', 'government'),
('reimbursement', 'builtin', 'government'),
('RENTAL HOUSING', 'builtin', 'government'),
('RENTAL PAYMENT', 'builtin', 'government'),
('RESEARCH GRANT', 'builtin', 'government'),
('REVENUE', 'builtin', 'government'),
('RISK MANAGEMENT', 'builtin', 'government'),
('ROAD COMMISSION', 'builtin', 'government'),
('secretary of state', 'builtin', 'government'),
('secretary of treasury', 'builtin', 'government'),
('SEWER AUTHORITY', 'builtin', 'government'),
('SHERIFF', 'builtin', 'government'),
('SIXTH DISTRICT', 'builtin', 'government'),
('SOCIAL SECURITY', 'builtin', 'government'),
('SPACE AGENCY', 'builtin', 'government'),
('STANDARDS AGENCY', 'builtin', 'government'),
('STATE', 'builtin', 'government'),
('STATE BAR', 'builtin', 'government'),
('STATE FARM', 'builtin', 'government'),
('STATE OF', 'builtin', 'government'),
('STATE TAX', 'builtin', 'government'),
('STATE TREASURER', 'builtin', 'government'),
('STREET OPENING PERMIT', 'builtin', 'government'),
('SUBSIDY', 'builtin', 'government'),
('SUPREME COURT', 'builtin', 'government'),
('TARIFF', 'builtin', 'government'),
('TAX', 'builtin', 'government'),
('tax collector', 'builtin', 'government'),
('TAX COMMISSION', 'builtin', 'government'),
('TEACHERS RETIREMENT', 'builtin', 'government'),
('THE COMMONWEALTH', 'builtin', 'government'),
('TJE COMPENSATION', 'builtin', 'government'),
('Town of', 'builtin', 'government'),
('TOWNSHIP', 'builtin', 'government'),
('TRADE COMMISSION', 'builtin', 'government'),
('TRANSACTION SETTLEMENT', 'builtin', 'government'),
('TRANSPORTATION', 'builtin', 'government'),
('TRANSPORTATION AUTHORITY', 'builtin', 'government'),
('TREASURER', 'builtin', 'government'),
('TREASURY', 'builtin', 'government'),
('TRIBAL', 'builtin', 'government'),
('U S DEPARTMENT', 'builtin', 'government'),
('U.S. DEPARTMENT', 'builtin', 'government'),
('united state treasury', 'builtin', 'government'),
('UNITED STATES', 'builtin', 'government'),
('us dept of education', 'builtin', 'government'),
('us postal service', 'builtin', 'government'),
('USDA', 'builtin', 'government'),
('UTILITIES', 'builtin', 'government'),
('UTILITY BOARD', 'builtin', 'government'),
('VA', 'builtin', 'government'),
('WATER', 'builtin', 'government'),
('WATER AUTHORITY', 'builtin', 'government'),
('WATER DISTRICT', 'builtin', 'government'),
('WATER FUND', 'builtin', 'government'),
('WELFARE', 'builtin', 'government'),
('WISCONSIN ENERGY', 'builtin', 'government'),
('WORKFORCE', 'builtin', 'government')
ON CONFLICT DO NOTHING;

-- Utility Keywords
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('AEP', 'builtin', 'utilities'),
('alabama power', 'builtin', 'utilities'),
('alagasco', 'builtin', 'utilities'),
('AMERICAN ELECTRIC', 'builtin', 'utilities'),
('archer energy', 'builtin', 'utilities'),
('ARIZONA PUBLIC SERVICE', 'builtin', 'utilities'),
('AURORA ENERGY', 'builtin', 'utilities'),
('AUSTIN ENERGY', 'builtin', 'utilities'),
('AVISTA', 'builtin', 'utilities'),
('CAROLINA POWER', 'builtin', 'utilities'),
('CENTRAL HUDSON', 'builtin', 'utilities'),
('CHARLOTTE WATER', 'builtin', 'utilities'),
('CITY LIGHT', 'builtin', 'utilities'),
('CITY UTILITIES', 'builtin', 'utilities'),
('CLARKE ENERGY', 'builtin', 'utilities'),
('CON EDISON', 'builtin', 'utilities'),
('CONSOLIDATED', 'builtin', 'utilities'),
('Constellation', 'builtin', 'utilities'),
('CONSUMERS ENERGY', 'builtin', 'utilities'),
('DECATUR UTILITIES', 'builtin', 'utilities'),
('DELAWARE POWER', 'builtin', 'utilities'),
('DES MOINES WATER', 'builtin', 'utilities'),
('DOMINION ENERGY', 'builtin', 'utilities'),
('DUKE ENERGY', 'builtin', 'utilities'),
('ELECTRIC', 'builtin', 'utilities'),
('ELECTRIC CO', 'builtin', 'utilities'),
('ELECTRIC CO‑OP', 'builtin', 'utilities'),
('ELECTRIC COOPERATIVE', 'builtin', 'utilities'),
('ELECTRICAL', 'builtin', 'utilities'),
('ELIZABETHTOWN GAS', 'builtin', 'utilities'),
('EMERA', 'builtin', 'utilities'),
('ENERGY', 'builtin', 'utilities'),
('ENTERGY', 'builtin', 'utilities'),
('EVERSOURCE', 'builtin', 'utilities'),
('FLORIDA POWER & LIGHT', 'builtin', 'utilities'),
('FORTIS', 'builtin', 'utilities'),
('GAS', 'builtin', 'utilities'),
('GAS CO', 'builtin', 'utilities'),
('GAS COMPANY', 'builtin', 'utilities'),
('GEORGIA POWER', 'builtin', 'utilities'),
('GREAT PLAINS ENERGY', 'builtin', 'utilities'),
('HYDRO', 'builtin', 'utilities'),
('KANSAS GAS', 'builtin', 'utilities'),
('MAINE POWER', 'builtin', 'utilities'),
('MADISON GAS', 'builtin', 'utilities'),
('MDC UTILITIES', 'builtin', 'utilities'),
('METRO WATER', 'builtin', 'utilities'),
('MINNESOTA POWER', 'builtin', 'utilities'),
('NATIONAL GRID', 'builtin', 'utilities'),
('NEW JERSEY UTILITIES', 'builtin', 'utilities'),
('NORTHERN NATURAL GAS', 'builtin', 'utilities'),
('NSTAR', 'builtin', 'utilities'),
('OG&E', 'builtin', 'utilities'),
('OIL', 'builtin', 'utilities'),
('ONCOR', 'builtin', 'utilities'),
('PACIFIC GAS & ELECTRIC', 'builtin', 'utilities'),
('PALO ALTO UTILITIES', 'builtin', 'utilities'),
('PEOPLES GAS', 'builtin', 'utilities'),
('PG&E', 'builtin', 'utilities'),
('POWER', 'builtin', 'utilities'),
('PPL ELECTRIC', 'builtin', 'utilities'),
('PROGRESSIVE ENERGY', 'builtin', 'utilities'),
('PUBLIC SERVICE COMPANY', 'builtin', 'utilities'),
('ROCKY MOUNTAIN POWER', 'builtin', 'utilities'),
('SALT RIVER PROJECT', 'builtin', 'utilities'),
('SOLAR', 'builtin', 'utilities'),
('SOUTH CAROLINA ELECTRIC', 'builtin', 'utilities'),
('SOUTHERN CALIFORNIA EDISON', 'builtin', 'utilities'),
('SOUTHERN COMPANY', 'builtin', 'utilities'),
('SOUTHWEST GAS', 'builtin', 'utilities'),
('TENNESSEE VALLEY AUTHORITY', 'builtin', 'utilities'),
('VISTRA', 'builtin', 'utilities'),
('WALNUT ENERGY', 'builtin', 'utilities'),
('WASTE MANAGEMENT', 'builtin', 'utilities'),
('WEC ENERGY', 'builtin', 'utilities'),
('WESTAR ENERGY', 'builtin', 'utilities'),
('WM SERVICES', 'builtin', 'utilities'),
('XCEL ENERGY', 'builtin', 'utilities')
ON CONFLICT DO NOTHING;

-- Technology & Telecom Keywords
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('TECHNOLOGY', 'builtin', 'technology'),
('SOFTWARE', 'builtin', 'technology'),
('HARDWARE', 'builtin', 'technology'),
('TECH', 'builtin', 'technology'),
('SYSTEMS', 'builtin', 'technology'),
('DATA', 'builtin', 'technology'),
('DIGITAL', 'builtin', 'technology'),
('COMPUTING', 'builtin', 'technology'),
('ELECTRONICS', 'builtin', 'technology'),
('TELECOM', 'builtin', 'technology'),
('TELECOMMUNICATIONS', 'builtin', 'technology'),
('INTERNET', 'builtin', 'technology'),
('WEB', 'builtin', 'technology'),
('MOBILE', 'builtin', 'technology'),
('WIRELESS', 'builtin', 'technology'),
('BROADBAND', 'builtin', 'technology'),
('NETWORK', 'builtin', 'technology'),
('CABLE', 'builtin', 'technology'),
('SATELLITE', 'builtin', 'technology'),
('FIBER', 'builtin', 'technology'),
('PHONE', 'builtin', 'technology'),
('CELLULAR', 'builtin', 'technology'),
('COMMUNICATIONS', 'builtin', 'technology'),
('AT&T', 'builtin', 'technology'),
('AT & T', 'builtin', 'technology'),
('AT AND T', 'builtin', 'technology'),
('ATT', 'builtin', 'technology'),
('AT T', 'builtin', 'technology'),
('AMERICAN TELEPHONE', 'builtin', 'technology'),
('AMERICAN TELEPHONE AND TELEGRAPH', 'builtin', 'technology'),
('AT&T INC', 'builtin', 'technology'),
('AT&T CORP', 'builtin', 'technology'),
('AT&T WIRELESS', 'builtin', 'technology'),
('AT&T MOBILITY', 'builtin', 'technology'),
('AT&T SERVICES', 'builtin', 'technology'),
('VERIZON', 'builtin', 'technology'),
('VERIZON WIRELESS', 'builtin', 'technology'),
('VERIZON COMMUNICATIONS', 'builtin', 'technology'),
('T-MOBILE', 'builtin', 'technology'),
('TMOBILE', 'builtin', 'technology'),
('T MOBILE', 'builtin', 'technology'),
('METRO PCS', 'builtin', 'technology'),
('METROPCS', 'builtin', 'technology'),
('SPRINT', 'builtin', 'technology'),
('SPRINT NEXTEL', 'builtin', 'technology'),
('US CELLULAR', 'builtin', 'technology'),
('CRICKET WIRELESS', 'builtin', 'technology'),
('COMCAST', 'builtin', 'technology'),
('XFINITY', 'builtin', 'technology'),
('TIME WARNER', 'builtin', 'technology'),
('CHARTER', 'builtin', 'technology'),
('SPECTRUM', 'builtin', 'technology'),
('COX COMMUNICATIONS', 'builtin', 'technology'),
('FRONTIER', 'builtin', 'technology'),
('CENTURYLINK', 'builtin', 'technology'),
('LUMEN', 'builtin', 'technology'),
('cox', 'builtin', 'technology'),
('CROWN CASTLE', 'builtin', 'technology'),
('CINCINNATI BELL', 'builtin', 'technology'),
('CHARTER COMMUNICATIONS', 'builtin', 'technology'),
('tmobile', 'builtin', 'technology'),
('t-mobile', 'builtin', 'technology'),
('T‑MOBILE', 'builtin', 'technology'),
('PHONE COMPANY', 'builtin', 'technology')
ON CONFLICT DO NOTHING;

-- Healthcare Keywords
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('AETNA', 'builtin', 'healthcare'),
('aflac', 'builtin', 'healthcare'),
('ANTHEM', 'builtin', 'healthcare'),
('BAYLOR SCOTT & WHITE', 'builtin', 'healthcare'),
('BENEFITS', 'builtin', 'healthcare'),
('BEREAVEMENT', 'builtin', 'healthcare'),
('BLUE CARE', 'builtin', 'healthcare'),
('BLUE CROSS', 'builtin', 'healthcare'),
('BLUE SHIELD', 'builtin', 'healthcare'),
('CENTENE', 'builtin', 'healthcare'),
('CIGNA', 'builtin', 'healthcare'),
('colonial life', 'builtin', 'healthcare'),
('DEACONESS', 'builtin', 'healthcare'),
('delta dental', 'builtin', 'healthcare'),
('EXCELLUS', 'builtin', 'healthcare'),
('HEALTHSPRING', 'builtin', 'healthcare'),
('HUMANA', 'builtin', 'healthcare'),
('MAGELLAN HEALTH', 'builtin', 'healthcare'),
('MCNA', 'builtin', 'healthcare'),
('MEDICAID', 'builtin', 'healthcare'),
('MEDICARE', 'builtin', 'healthcare'),
('MEMORIAL HOSPITAL PAYROLL', 'builtin', 'healthcare')
ON CONFLICT DO NOTHING;

-- Payroll Service Keywords
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('ADP', 'builtin', 'payroll'),
('CBIZ PAYROLL', 'builtin', 'payroll'),
('CERIDIAN', 'builtin', 'payroll'),
('ESA PAYROLL', 'builtin', 'payroll'),
('G&K SERVICES', 'builtin', 'payroll'),
('GALLAGHER BENEFIT', 'builtin', 'payroll'),
('GUSTO', 'builtin', 'payroll'),
('MOSAIC PAYMENTS', 'builtin', 'payroll'),
('NCR', 'builtin', 'payroll'),
('PAYCHEX', 'builtin', 'payroll'),
('PAYCOM', 'builtin', 'payroll'),
('PAYLOCITY', 'builtin', 'payroll'),
('PAYMENTUS', 'builtin', 'payroll'),
('PAYROLL', 'builtin', 'payroll'),
('PAYROLL SERVICE', 'builtin', 'payroll'),
('SEDGWICK', 'builtin', 'payroll'),
('SYSCO', 'builtin', 'payroll'),
('TRINET', 'builtin', 'payroll'),
('TUTOR PERINI PAYROLL', 'builtin', 'payroll'),
('UKG', 'builtin', 'payroll'),
('us foods', 'builtin', 'payroll')
ON CONFLICT DO NOTHING;

-- Automotive Keywords
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('CARMAX AUTO FINANCE', 'builtin', 'automotive'),
('CATERPILLAR FINANCIAL', 'builtin', 'automotive'),
('CHEVRON CREDIT', 'builtin', 'automotive'),
('ELEMENT FLEET', 'builtin', 'automotive'),
('ERICSSON CREDIT', 'builtin', 'automotive'),
('GM', 'builtin', 'automotive'),
('GM FINANCIAL', 'builtin', 'automotive'),
('HONDA', 'builtin', 'automotive'),
('HONDA FINANCE', 'builtin', 'automotive'),
('HYUNDAI', 'builtin', 'automotive'),
('KIA', 'builtin', 'automotive'),
('MAZDA', 'builtin', 'automotive'),
('MERCEDES BENZ FINANCIAL', 'builtin', 'automotive'),
('NISSAN MOTOR ACCEPTANCE', 'builtin', 'automotive'),
('PARKER HANNIFIN CREDIT', 'builtin', 'automotive'),
('STELLANTIS', 'builtin', 'automotive'),
('TOYOTA', 'builtin', 'automotive'),
('TOYOTA FINANCIAL', 'builtin', 'automotive')
ON CONFLICT DO NOTHING;

-- Real Estate & Property Management
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('REAL ESTATE', 'builtin', 'real_estate'),
('PROPERTY MANAGEMENT', 'builtin', 'real_estate'),
('REALTY', 'builtin', 'real_estate'),
('REALTOR', 'builtin', 'real_estate'),
('APARTMENTS', 'builtin', 'real_estate'),
('CONDOS', 'builtin', 'real_estate'),
('HOUSING', 'builtin', 'real_estate'),
('RENTAL', 'builtin', 'real_estate'),
('LEASE', 'builtin', 'real_estate'),
('MORTGAGE', 'builtin', 'real_estate'),
('ESCROW', 'builtin', 'real_estate'),
('TITLE COMPANY', 'builtin', 'real_estate'),
('BROKER', 'builtin', 'real_estate'),
('AGENT', 'builtin', 'real_estate'),
('COLDWELL BANKER', 'builtin', 'real_estate'),
('CENTURY 21', 'builtin', 'real_estate'),
('RE/MAX', 'builtin', 'real_estate'),
('KELLER WILLIAMS', 'builtin', 'real_estate'),
('ZILLOW', 'builtin', 'real_estate'),
('TRULIA', 'builtin', 'real_estate'),
('PROPERTY MANAGER', 'builtin', 'real_estate'),
('LANDLORD', 'builtin', 'real_estate'),
('TENANT', 'builtin', 'real_estate'),
('HOMEOWNER', 'builtin', 'real_estate'),
('FORECLOSURE', 'builtin', 'real_estate')
ON CONFLICT DO NOTHING;

-- Transportation & Logistics
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('FEDEX', 'builtin', 'transportation'),
('UPS', 'builtin', 'transportation'),
('DHL', 'builtin', 'transportation'),
('USPS', 'builtin', 'transportation'),
('SHIPPING', 'builtin', 'transportation'),
('FREIGHT', 'builtin', 'transportation'),
('LOGISTICS', 'builtin', 'transportation'),
('DELIVERY', 'builtin', 'transportation'),
('TRANSPORT', 'builtin', 'transportation'),
('TRUCKING', 'builtin', 'transportation'),
('AIRLINE', 'builtin', 'transportation'),
('AIRPORT', 'builtin', 'transportation'),
('BUS', 'builtin', 'transportation'),
('METRO', 'builtin', 'transportation'),
('SUBWAY', 'builtin', 'transportation'),
('TAXI', 'builtin', 'transportation'),
('UBER', 'builtin', 'transportation'),
('LYFT', 'builtin', 'transportation'),
('RENTAL CAR', 'builtin', 'transportation'),
('MOVING COMPANY', 'builtin', 'transportation'),
('AMERICAN AIRLINES', 'builtin', 'transportation'),
('DELTA', 'builtin', 'transportation'),
('UNITED AIRLINES', 'builtin', 'transportation'),
('SOUTHWEST', 'builtin', 'transportation'),
('JETBLUE', 'builtin', 'transportation')
ON CONFLICT DO NOTHING;

-- Food & Restaurant Chains
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('MCDONALDS', 'builtin', 'food_restaurant'),
('BURGER KING', 'builtin', 'food_restaurant'),
('SUBWAY', 'builtin', 'food_restaurant'),
('STARBUCKS', 'builtin', 'food_restaurant'),
('KFC', 'builtin', 'food_restaurant'),
('PIZZA HUT', 'builtin', 'food_restaurant'),
('DOMINOS', 'builtin', 'food_restaurant'),
('TACO BELL', 'builtin', 'food_restaurant'),
('WENDYS', 'builtin', 'food_restaurant'),
('CHIPOTLE', 'builtin', 'food_restaurant'),
('PANERA', 'builtin', 'food_restaurant'),
('DUNKIN', 'builtin', 'food_restaurant'),
('RESTAURANT', 'builtin', 'food_restaurant'),
('CAFE', 'builtin', 'food_restaurant'),
('DINER', 'builtin', 'food_restaurant'),
('BISTRO', 'builtin', 'food_restaurant'),
('GRILL', 'builtin', 'food_restaurant'),
('BAKERY', 'builtin', 'food_restaurant'),
('CATERING', 'builtin', 'food_restaurant'),
('FOOD SERVICE', 'builtin', 'food_restaurant'),
('OLIVE GARDEN', 'builtin', 'food_restaurant'),
('APPLEBEES', 'builtin', 'food_restaurant'),
('CHILIS', 'builtin', 'food_restaurant'),
('OUTBACK', 'builtin', 'food_restaurant'),
('RED LOBSTER', 'builtin', 'food_restaurant')
ON CONFLICT DO NOTHING;

-- Retail Stores & Chains
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('WALMART', 'builtin', 'retail'),
('TARGET', 'builtin', 'retail'),
('AMAZON', 'builtin', 'retail'),
('COSTCO', 'builtin', 'retail'),
('SAMS CLUB', 'builtin', 'retail'),
('HOME DEPOT', 'builtin', 'retail'),
('LOWES', 'builtin', 'retail'),
('BEST BUY', 'builtin', 'retail'),
('MACYS', 'builtin', 'retail'),
('NORDSTROM', 'builtin', 'retail'),
('KOHLS', 'builtin', 'retail'),
('JC PENNEY', 'builtin', 'retail'),
('SEARS', 'builtin', 'retail'),
('CVS', 'builtin', 'retail'),
('WALGREENS', 'builtin', 'retail'),
('RITE AID', 'builtin', 'retail'),
('GROCERY STORE', 'builtin', 'retail'),
('SUPERMARKET', 'builtin', 'retail'),
('KROGER', 'builtin', 'retail'),
('SAFEWAY', 'builtin', 'retail'),
('PUBLIX', 'builtin', 'retail'),
('WHOLE FOODS', 'builtin', 'retail'),
('TRADER JOES', 'builtin', 'retail'),
('DOLLAR TREE', 'builtin', 'retail'),
('DOLLAR GENERAL', 'builtin', 'retail'),
('FAMILY DOLLAR', 'builtin', 'retail'),
('PETCO', 'builtin', 'retail'),
('PETSMART', 'builtin', 'retail'),
('STAPLES', 'builtin', 'retail'),
('OFFICE DEPOT', 'builtin', 'retail')
ON CONFLICT DO NOTHING;

-- Entertainment & Media
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('DISNEY', 'builtin', 'entertainment'),
('NETFLIX', 'builtin', 'entertainment'),
('HULU', 'builtin', 'entertainment'),
('HBO', 'builtin', 'entertainment'),
('ESPN', 'builtin', 'entertainment'),
('NBC', 'builtin', 'entertainment'),
('CBS', 'builtin', 'entertainment'),
('ABC', 'builtin', 'entertainment'),
('FOX', 'builtin', 'entertainment'),
('CNN', 'builtin', 'entertainment'),
('ENTERTAINMENT', 'builtin', 'entertainment'),
('MEDIA', 'builtin', 'entertainment'),
('BROADCASTING', 'builtin', 'entertainment'),
('TELEVISION', 'builtin', 'entertainment'),
('RADIO', 'builtin', 'entertainment'),
('MUSIC', 'builtin', 'entertainment'),
('SPOTIFY', 'builtin', 'entertainment'),
('APPLE MUSIC', 'builtin', 'entertainment'),
('YOUTUBE', 'builtin', 'entertainment'),
('PARAMOUNT', 'builtin', 'entertainment'),
('UNIVERSAL', 'builtin', 'entertainment'),
('SONY', 'builtin', 'entertainment'),
('WARNER', 'builtin', 'entertainment'),
('COMCAST NBC', 'builtin', 'entertainment'),
('VIACOM', 'builtin', 'entertainment')
ON CONFLICT DO NOTHING;

-- Non-Profit Organizations
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('RED CROSS', 'builtin', 'nonprofit'),
('SALVATION ARMY', 'builtin', 'nonprofit'),
('UNITED WAY', 'builtin', 'nonprofit'),
('GOODWILL', 'builtin', 'nonprofit'),
('YMCA', 'builtin', 'nonprofit'),
('HABITAT FOR HUMANITY', 'builtin', 'nonprofit'),
('AMERICAN CANCER SOCIETY', 'builtin', 'nonprofit'),
('MARCH OF DIMES', 'builtin', 'nonprofit'),
('NONPROFIT', 'builtin', 'nonprofit'),
('NON-PROFIT', 'builtin', 'nonprofit'),
('CHARITY', 'builtin', 'nonprofit'),
('FOUNDATION', 'builtin', 'nonprofit'),
('CHURCH', 'builtin', 'nonprofit'),
('SYNAGOGUE', 'builtin', 'nonprofit'),
('MOSQUE', 'builtin', 'nonprofit'),
('TEMPLE', 'builtin', 'nonprofit'),
('RELIGIOUS', 'builtin', 'nonprofit'),
('DONATION', 'builtin', 'nonprofit'),
('VOLUNTEER', 'builtin', 'nonprofit'),
('HUMANITARIAN', 'builtin', 'nonprofit')
ON CONFLICT DO NOTHING;

-- Manufacturing & Industrial
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('BOEING', 'builtin', 'manufacturing'),
('LOCKHEED MARTIN', 'builtin', 'manufacturing'),
('GENERAL ELECTRIC', 'builtin', 'manufacturing'),
('CATERPILLAR', 'builtin', 'manufacturing'),
('JOHN DEERE', 'builtin', 'manufacturing'),
('3M', 'builtin', 'manufacturing'),
('HONEYWELL', 'builtin', 'manufacturing'),
('DUPONT', 'builtin', 'manufacturing'),
('DOW CHEMICAL', 'builtin', 'manufacturing'),
('MANUFACTURING', 'builtin', 'manufacturing'),
('FACTORY', 'builtin', 'manufacturing'),
('INDUSTRIAL', 'builtin', 'manufacturing'),
('ASSEMBLY', 'builtin', 'manufacturing'),
('PRODUCTION', 'builtin', 'manufacturing'),
('STEEL', 'builtin', 'manufacturing'),
('ALUMINUM', 'builtin', 'manufacturing'),
('CHEMICAL', 'builtin', 'manufacturing'),
('PHARMACEUTICAL', 'builtin', 'manufacturing'),
('PFIZER', 'builtin', 'manufacturing'),
('JOHNSON & JOHNSON', 'builtin', 'manufacturing')
ON CONFLICT DO NOTHING;

-- Oil & Gas Companies
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('EXXON', 'builtin', 'oil_gas'),
('CHEVRON', 'builtin', 'oil_gas'),
('BP', 'builtin', 'oil_gas'),
('SHELL', 'builtin', 'oil_gas'),
('CONOCO PHILLIPS', 'builtin', 'oil_gas'),
('MARATHON', 'builtin', 'oil_gas'),
('VALERO', 'builtin', 'oil_gas'),
('PHILLIPS 66', 'builtin', 'oil_gas'),
('KINDER MORGAN', 'builtin', 'oil_gas'),
('ENBRIDGE', 'builtin', 'oil_gas'),
('PIPELINE', 'builtin', 'oil_gas'),
('REFINERY', 'builtin', 'oil_gas'),
('PETROLEUM', 'builtin', 'oil_gas'),
('NATURAL GAS', 'builtin', 'oil_gas'),
('CRUDE OIL', 'builtin', 'oil_gas'),
('EXPLORATION', 'builtin', 'oil_gas'),
('DRILLING', 'builtin', 'oil_gas'),
('FRACKING', 'builtin', 'oil_gas'),
('ENERGY COMPANY', 'builtin', 'oil_gas'),
('FOSSIL FUEL', 'builtin', 'oil_gas')
ON CONFLICT DO NOTHING;

-- Professional Services
INSERT INTO exclusion_keywords (keyword, keyword_type, category) VALUES
('KPMG', 'builtin', 'professional_services'),
('DELOITTE', 'builtin', 'professional_services'),
('ERNST & YOUNG', 'builtin', 'professional_services'),
('PRICEWATERHOUSECOOPERS', 'builtin', 'professional_services'),
('PWC', 'builtin', 'professional_services'),
('MCKINSEY', 'builtin', 'professional_services'),
('BOSTON CONSULTING', 'builtin', 'professional_services'),
('ACCENTURE', 'builtin', 'professional_services'),
('CONSULTING', 'builtin', 'professional_services'),
('ACCOUNTING FIRM', 'builtin', 'professional_services'),
('LAW FIRM', 'builtin', 'professional_services'),
('LEGAL SERVICES', 'builtin', 'professional_services'),
('ATTORNEY', 'builtin', 'professional_services'),
('LAWYER', 'builtin', 'professional_services'),
('PARALEGAL', 'builtin', 'professional_services'),
('AUDIT FIRM', 'builtin', 'professional_services'),
('TAX PREPARATION', 'builtin', 'professional_services'),
('H&R BLOCK', 'builtin', 'professional_services'),
('JACKSON HEWITT', 'builtin', 'professional_services'),
('ENGINEERING FIRM', 'builtin', 'professional_services')
ON CONFLICT DO NOTHING;