// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syybywjvvwwiecysfuey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5eWJ5d2p2dnd3aWVjeXNmdWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzU0NDYsImV4cCI6MjA2NTI1MTQ0Nn0.-km4JEbq4DcjKvX2jsifKVVZAvjLHCo35wZxSweOo9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);